### PR TITLE
Tests for prometheus collectors.

### PR DESCRIPTION
**Pull request by derekpierre**
**Type of PR:**
- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [X] Other

**Required reviews:** 
- [ ] 1
- [X] 2
- [ ] 3

**What this does:**
> High-level idea of the changes introduced in this PR. 
> List relevant API changes (if any), as well as related PRs and issues.

Adds testing for prometheus collectors.

**Issues fixed/closed:**
> - Fixes #...

Related to #2590 - these tests would have prevented missing that bug.

**Why it's needed:**
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!

**Notes for reviewers:**
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from reviewers?

I don't think we need a newsfragment for this internal change.

### CODE REVIEW

**Review by vzotova — APPROVED** [review]

**Review by KPrasch — COMMENTED** [review]
Are these tests included in a CI job?

**Comment by derekpierre** [comment]
> Are these tests included in a CI job?

Ah, you're right. I took it for granted since there was a `utilities/test_concurrency.py` file already, but that doesn't seem to be run either. Presumably, I'll have to modify the `.circleci/config.yml` file...?

**Comment by derekpierre** [comment]
> Are these tests included in a CI job?

@KPrasch should be good now - https://app.circleci.com/pipelines/github/nucypher/nucypher/7360/workflows/1811baac-2de1-41a2-9126-f76ad6f8337f/jobs/124912/steps

**Review by KPrasch — APPROVED** [review]
🤠

**Pull request merged**
