### PR TITLE
Fixes stake CLI name errors

### PR DESCRIPTION
**Pull request by KPrasch**
**Type of PR:**
Bugfixes

**Required reviews:** 
1

### CODE REVIEW

**Review by derekpierre — APPROVED** [review]
🎸

**Review by cygnusv — APPROVED** [review]
Great, I noticed this error today. I bypassed it by passing the staking address as a flag.

**Comment by KPrasch** [comment]
> Great, I noticed this error today. I bypassed it by passing the staking address as a flag.

What command were you running - I'm not sure I fixed all occurrences.

**Comment by cygnusv** [comment]
> > Great, I noticed this error today. I bypassed it by passing the staking address as a flag.
> 
> What command were you running? I'm not sure I fixed all occurrences.

`nucypher stake remove-unused`

**Pull request merged**
