### PR TITLE
Fixes #828 - Allow solc install script to crash instead of report success 

### LINKED ISSUE #828: install_solc.sh outputs "Success" even when it fails
```
$ ./scripts/installation/install_solc.sh 
Downloading solidity compiler binary to: /home/david/.local/share/virtualenvs/nucypher-rz58eSz8/bin/solc
--2019-03-13 12:48:45--  https://github.com/ethereum/solidity/releases/download/v0.5.3/solc-static-linux
Resolving github.com (github.com)... 192.30.253.113, 192.30.253.112
Connecting to github.com (github.com)|192.30.253.113|:443... connected.
ERROR: cannot verify github.com's certificate, issued by ‘CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
Setting executable permission on /home/david/.local/share/virtualenvs/nucypher-rz58eSz8/bin/solc
Successfully Installed solc 0.5.3


$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.24+commit.e67f0147.Linux.g++
```

### PR DESCRIPTION
**Pull request by KPrasch**
Fixes #828 (Needs testing on OSX)

### CODE REVIEW

**Comment by michwill** [comment]
Really, why do we install solc in `~/.local` rather than in virtual environment?

**Comment by KPrasch** [comment]
> Really, why do we install solc in ~/.local rather than in virtual environment?
Hmm, yeah docker seems to be upset about this too.

**Comment by michwill** [comment]
If we are to run it from virtual environment, we can do SOL_BIN_PATH="$(dirname `which python`)/solc" (and it'll work with non-pipenv installation too then)

**Comment by KPrasch** [comment]
I can confirm that docker commands like `(nucypher) k@nova:~/Git/nucypher$ sudo docker-compose -f dev/docker/docker-compose.yml run nucypher-dev pytest tests/characters
` are able to utilize this version of solc installation.

**Pull request merged**
