### PR TITLE
Porter Error Handling for `/retrieve_cfrags` endpoint

### PR DESCRIPTION
**Pull request by derekpierre**
**Type of PR:**
- [ ] Bugfix
- [X] Feature
- [ ] Documentation
- [ ] Other

**Required reviews:** 
- [ ] 1
- [X] 2
- [ ] 3

**What this does:**
Initial schema for communicating errors that occur during `/retrieve_cfrags` back to the caller.

**Issues fixed/closed:**
Fixes https://github.com/nucypher/tdec/issues/57
Fixes https://github.com/nucypher/nucypher/issues/2789

**Why it's needed:**
Porter needs to provide better feedback on errors that occur during retrieval.

Initial version looks like:
```json
 "result": {
        "retrieval_results": [
            {
                "cfrags": {
                    // ...
                },
                "errors": {
                    "<ursula_address>": "<error_message>",
                    // category I - network is down, ursulas are wrong, everything is falling apart
                    "<ursula>": "Internal Server Error",
                     // sir, stop breaking the porter plz
                    "<ursula>": "Something wrong with your parameters buddy: ciphertext is undefined",
                    // condition verification on ursula - actionable feedback for the user
                    "<ursula>": "Decryption conditions not satisfied",
                    // auth - actionable feedback for the user; stale auth
                    "<ursula>": "Context variable data could not be verified"
                }
            }
        ]
    }, 
    "version": "6.1.0"
```

**Notes for reviewers:**

### CODE REVIEW

**Review by piotr-roslaniec — APPROVED** [review]
LGTM

Testing this locally now, but I see no reasons to move forward with this PR

**Comment by piotr-roslaniec** [comment]
Result from local testing, for posterity:
```
{
   "result":{
      "retrieval_results":[
         {
            "cfrags": {},
            "errors": {
               "0x53f72787d33b29b0f1d5485f4b0B1281FbE8e613":"Ursula ((Ursula)\u21c0SteelBlue Two LightGray Yankee\u21bd (0x53f72787d33b29b0f1d5485f4b0B1281FbE8e613)) seems to be down while trying to complete ReencryptionRequest: <nucypher_core.ReencryptionRequest object at 0x7f605c003e50>",
               "0xb0488A74Ad06DC0DA2031cBD720537C48d63EfD7":"Ursula ((Ursula)\u21c0PeachPuff Eight DarkOrchid Tango\u21bd (0xb0488A74Ad06DC0DA2031cBD720537C48d63EfD7)) seems to be down while trying to complete ReencryptionRequest: <nucypher_core.ReencryptionRequest object at 0x7f605c00a450>",
               "0xbC40aE0041b9b0AE3D012a40492B42d1E0EE294F":"Ursula ((Ursula)\u21c0DarkMagenta Tango Navy Whiskey\u21bd (0xbC40aE0041b9b0AE3D012a40492B42d1E0EE294F)) seems to be down while trying to complete ReencryptionRequest: <nucypher_core.ReencryptionRequest object at 0x7f605c00c4b0>",
               "0xbD27e413b1460d51fe1b6b4b64E5dAFC3541b12B":"Ursula ((Ursula)\u21c0DarkSlateBlue Romeo Gold Mike\u21bd (0xbD27e413b1460d51fe1b6b4b64E5dAFC3541b12B)) seems to be down while trying to complete ReencryptionRequest: <nucypher_core.ReencryptionRequest object at 0x7f605c00e890>"
            }
         }
      ]
   },
   "version":"6.1.0"
}
```

**Comment by piotr-roslaniec** [comment]
I just have one comment. So earlier today I created an impossible condition that resulted in failed decryption
```
2022-09-22T11:23:08+0000 [RetrievalClient#warn] Ursula (Ursula)⇀DarkMagenta Tango Navy Whiskey↽ (0xbC40aE0041b9b0AE3D012a40492B42d1E0EE294F) failed to reencrypt: b''
2022-09-22T11:23:08+0000 [RetrievalClient#warn] Ursula (Ursula)⇀PeachPuff Eight DarkOrchid Tango↽ (0xb0488A74Ad06DC0DA2031cBD720537C48d63EfD7) failed to reencrypt: b''
2022-09-22T11:23:09+0000 [RetrievalClient#warn] Ursula (Ursula)⇀DarkSlateBlue Romeo Gold Mike↽ (0xbD27e413b1460d51fe1b6b4b64E5dAFC3541b12B) failed to reencrypt: b''
2022-09-22T11:23:10+0000 [RetrievalClient#warn] Ursula (Ursula)⇀SteelBlue Two LightGray Yankee↽ (0x53f72787d33b29b0f1d5485f4b0B1281FbE8e613) failed to reencrypt: b''
```
The results from `/retrieve_cfrags` were:
```
{
   "result":{
      "retrieval_results":[
         {
            "cfrags":{
               
            },
            "errors":{
               "0xbD27e413b1460d51fe1b6b4b64E5dAFC3541b12B":"b''",
               "0xbC40aE0041b9b0AE3D012a40492B42d1E0EE294F":"b''",
               "0x53f72787d33b29b0f1d5485f4b0B1281FbE8e613":"b''",
               "0xb0488A74Ad06DC0DA2031cBD720537C48d63EfD7":"b''"
            }
         }
      ]
   },
   "version":"6.1.0"
}
```
I think if we could have `failed to reencrypt` as a part of error string returned from API (and whatever errors are thrown - in their entirety) that would be a significant improvement.

If we can't have that or it's too complex of a request at this time, I think I can also work with the API returning `b''`.

**Comment by derekpierre** [comment]
@piotr-roslaniec - addressed via https://github.com/nucypher/nucypher/pull/2973/commits/9fd5ed540599ff496d6d8c6f57f310c90dae7728

**Comment by derekpierre** [comment]
@piotr-roslaniec 's testing has been positive, so merging. Follow-up PR started for issue with ERC721 support - #2974 .

**Pull request merged**
