### PR TITLE
[WIP] Giving codecov a spin.

### PR DESCRIPTION
**Pull request by jMyles**

### CODE REVIEW

**Comment by KPrasch** [comment]
Looks like the circleCI codecov orb is getting snagged on some HTML template in tests: https://circleci.com/gh/nucypher/nucypher/20033#tests/containers/2

**Comment by vepkenez** [comment]
I don't understand what is going on in this PR.... why are there so many seemingly unrelated commits?

**Comment by jMyles** [comment]
@vepkenez: It needs a rebase.  I had intended to work on this, but CircleCI is having some issues right now so it doesn't make sense.  Instead I'm doing Bob stuff for a bit.  When I circle back around, I'll rebase it.

**Comment by tuxxy** [comment]
It doesn't need a rebase, just switched branches back to back and it fixes it. :)

**Comment by vepkenez** [comment]
I guess part of this should be to integrate https://www.codecov.io ?

**Comment by KPrasch** [comment]
I'd love to see this merged soon!

**Comment by KPrasch** [comment]
Cherry-picked commits; Moving to PR #910

**Pull request closed without merging**
