### PR TITLE
Fix bug with merged sub-stake and migration (when last period is 1)

### PR DESCRIPTION
**Pull request by vzotova**
**Type of PR:**
- [X] Bugfix

**Required reviews:** 
- [X] 3

**What this does:**
Fix small bug when inactive sub-stake become active for current period only after migration. It leads to lock tokens (without reward) when it should not

### CODE REVIEW

**Review by KPrasch — APPROVED** [review]
Thank You @vzotova!

**Review by derekpierre — APPROVED** [review]
🎸

**Review by arjunhassard — APPROVED** [review]
🪕 good catch

**Comment by KPrasch** [comment]
Note for reviewers: The failing CLI test on CI is unrelated.

**Review by cygnusv — APPROVED** [review]

**Pull request merged**
