### PR TITLE
[Concept] Client layer middleware, CLI Signer handling, Stale Deprecations

### PR DESCRIPTION
**Pull request by KPrasch**
Based on #2335, Includes #2331, working to advance #2141 

###### Clients & Interfaces
- Rework of web3 middleware management on the client layer
- Introduces stalecheck middleware (dual speed, longer syncing delay permitted in tests)
- Implement client-layer default gas strategies via inhert-and-override
- Auto-detection of POA  middleware requirement
- Avoid nonce reusage in tests with block cache disable/reconfigure
- Simplifies interface connection logic

###### Signer handling
- Remove implicit default signer from configuration flow and internally
- Understand `--signer` as a required option where possible

###### Ursula 
- `fire_and_forget ` -> `wait_for_receipt`
- `WorkTracker` tracks pending worker commitment transactions by hash (needs follow-up)

###### Tests & Code Quality
- Completes test dummy mocking integration for Interfaces, Clients, Providers, and Web3
- Organize and optimize imports

###### CLI
- Numerous language and formatting improvements found while manually testing `stake` and `ursula` command.

##### Deprecation

- `--poa` flag (in favor of auto-detection)
- `--geth` Internal geth process management (stale, unused)
- `NuCypherGethDevProcess` and friends (unused, stale)
- `ContractAdministrator.deploy_network_contracts` (stale, too optimistic, use `Testerchain.bootstrap_network` in tests)
- `nucypher-deploy contracts` Automated deployment series (stale, save actions and utils)
- `EthereumClient.sync` - RPC sync polling (unused)
- `actors.Wallet` (replaces with signers and dependency injection)
- `BlockchainInterface.to_dict` and `BlockchainInterface.from_dict` (unused)

### CODE REVIEW

**Comment by KPrasch** [comment]
I have outstanding work based on this PR both for gas strategies and for worker tracking transaction hashes.  Removing WIP to begin the feedback cycle, although those areas remain subject to change, and follow-up.

**Comment by cygnusv** [comment]
@KPrasch Looks like this PR is now with a lot of conflicts coming from the urgent changes in #2389. 
I was thinking, what do you think if you extract some stuff from this PR to an independent PR focused in obvious deprecations? E.g.:

- --geth Internal geth process management (stale, unused)
- NuCypherGethDevProcess and friends (unused, stale)
- ContractAdministrator.deploy_network_contracts (stale, too optimistic, use Testerchain.bootstrap_network in tests)
- nucypher-deploy contracts Automated deployment series (stale, save actions and utils)

This can reduce the amount for this PR later and facilitate the review process (maybe even the rebases)

**Comment by KPrasch** [comment]
Marking do not merge due to to divergence and staleness :-( - to be salvaged for spare parts and reincorporated in future work, then closed.

**Comment by KPrasch** [comment]
Unfortunately I need to close this PR - it was not accepted before massive divergence.  :-(

**Pull request closed without merging**
