### PR TITLE
dependabot helper files

### PR DESCRIPTION
**Pull request by chaos-ui**
**Type of PR:**
- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Other

**Required reviews:** 
- [ ] 1
- [ ] 2
- [X] 3

**What this does:**
> High-level idea of the changes introduced in this PR. 
> List relevant API changes (if any), as well as related PRs and issues.

**Issues fixed/closed:**
> - Fixes #...

**Why it's needed:**
> Explain how this PR fits in the greater context of the NuCypher Network.
> E.g., if this PR address a `nucypher/productdev` issue, let reviewers know!

**Notes for reviewers:**
> What should reviewers focus on? 
> Is there a particular commit/function/section of your PR that requires more attention from reviewers?

### CODE REVIEW

**Comment by KPrasch** [comment]
Hi there @chaos-ui!  Please fill out the PR description so we know what he intended changes are.

**Comment by KPrasch** [comment]
Sorry @chaos-ui - It's too unclear what the intended changes are here.  Is it to remove images from our codebase?

Feel free to reopen this PR with a completed description if you still want to contribute.

**Comment by chaos-ui** [comment]
Hello, this change optimizes images to minimal compression and was suggested via Imgbot as PR

**Comment by chaos-ui** [comment]
https://github.com/nucypher/nucypher/commit/be1781f2792a68493ac3c25052ac20b5bba151a1

**Pull request closed without merging**
