### PR TITLE
Further reinforce hypothetical nature of WorkLock example scenarios

### PR DESCRIPTION
**Pull request by derekpierre**
The values used in the examples can be modified at a later date, since it takes time to determine good values for the scenarios. As a stop-gap, I will overly highlight the `hypothetical` nature of the examples even more, until I can work through some examples with actual values.

Updated page:

Screen Shot 2020-08-25 at 2 39 10 PM

### CODE REVIEW

**Review by cygnusv — APPROVED** [review]
Something unrelated to this PR: in Scenario 3 section, the formatting of `whale_1` and `whale_2` doesn't show correctly because it's already in a paragraph surrounded by `** ... **`. Maybe there's a way to correct that?

**Comment by derekpierre** [comment]
@cygnusv `rst` is weird about nesting styles. I tried before but to no avail.

**Comment by mswilkison** [comment]
Unfortunately, I don't know if the disclaimer about the hypothetical natures is getting through. WDYT about changing to the actual numbers?

**Comment by derekpierre** [comment]
👍 I'll try to put together some new examples and prioritize it for tomorrow. This was only meant as a stop gap.

**Pull request merged**
