### PR TITLE
[Do Not Merge] Threshold / PREApplication Worker

### PR DESCRIPTION
**Pull request by KPrasch**
**Type of PR:**
Feature

**Required reviews:** 
3

**What this does:**

- Includes the `SimplePREApplication` compilation and fixturization in the test suite.
- Introduces `PREApplicationAgent`
- Introduces `PREApplicationDeployer` (used for testing, subject to future removal)
- Introduces `ThreholdWorker`
- Introduces `SimplePREWorkTracker`

**Why it's needed:**
- Node compatibility with threshold network pre application.
- Will be used for contract interactions between `Ursula` and `PREApplication` (threshold network)

**Notes for reviewers:**
- Based on #2838 
- Needs final values for constructor parameters, using placeholders for now
- Needs additional integration testing once the contract is more developed
- `PREApplicationDeployer` is a temporary testing utility which will be replaced by brownie in the future.

### CODE REVIEW

**Comment by vepkenez** [comment]
Hey, should we merge my PR into this?
I can rebase again.

**Comment by KPrasch** [comment]
Yep, let's merge into this PR and continue iterating.

**Comment by vepkenez** [comment]
I have some more stuff but it's not ready. What's pushed so far is "clean".

**Comment by KPrasch** [comment]
subsumed by #2857

**Pull request closed without merging**
