### PR TITLE
Use released `nucypher-core@0.12.0` package

### PR DESCRIPTION
**Pull request by piotr-roslaniec**
**Type of PR:**
- Other

**Required reviews:** 
- 1

**What this does:**
- Replaces GH repository in project dependencies with a released `nucypher-core` package

- [ ] Relock deps

### CODE REVIEW

**Comment by piotr-roslaniec** [comment]
Those CI failures don't seem related to `nucypher-core`.

**Comment by derekpierre** [comment]
> Those CI failures don't seem related to `nucypher-core`.

Seems to be changes to `nucypher-contracts` affecting the acceptance tests.
```
 AttributeError: Dependency project 'nucypher-contracts' has no contract 'ThresholdStakingForPREApplicationMock'.
 ```

Side note: we should consider doing a relocking of overall dependencies instead of just `nucypher-core`. i.e. we should just update the Pipfile to use `nucypher-core` 0.12.0, and then try running `scripts/dependencies/relock_dependencies.sh` to regenerate the [dev-]requirements.txt files.

**Comment by derekpierre** [comment]
Took a deeper look at this.

While I would like a full relock of dependencies - there are some issues with that related to eip-structs 712, and eth-accounts versions causing dependency conflicts which I believe @jMyles seems to be looking into - it's good to get this github dependency out of our code in the interim.

I've tested this change locally using a modified ape-config for acceptance tests to use https://github.com/derekpierre/nucypher-contracts/tree/local-testing instead of `main` to exclude the latest Coordinator changes from https://github.com/nucypher/nucypher-contracts/pull/92; the acceptance tests pass. 

I'd like to have this merged anyway given that the update to the `nucypher-core` github dependency should have occurred before #3194 was merged, and is essentially the same code as `0.12.0` anyway. The change is pretty self-contained.

I'm approving for merge. (cc @KPrasch)

**Review by derekpierre — APPROVED** [review]
🎸

**Review by KPrasch — APPROVED** [review]

**Pull request merged**
