### PR TITLE
[WIP-Release] I mean, you don't bring your own branches to Federated.

### PR DESCRIPTION
**Pull request by jMyles**

### CODE REVIEW

**Comment by KPrasch** [comment]
Well thats a nice clean merge.

**Comment by cygnusv** [comment]
Is this meant to be closed or reviewed?

**Comment by KPrasch** [comment]
Will this be closed in favor of #608 ?

**Comment by jMyles** [comment]
This is pretty clearly not going anywhere.  #608 is the canonical federated final release at this point.

**Pull request closed without merging**
