### PR TITLE
Hardcoding a felix NU transfer gas limit.

### PR DESCRIPTION
**Pull request by KPrasch**

### CODE REVIEW

**Comment by KPrasch** [comment]
I dont know if this is a fix yet - putting it here for now.

**Comment by michwill** [comment]
Ah no, it must be a transaction count. Well, in such case, we have to have nonce=None, and get it from blockchain when it's None, otherwise increase by 1 every next transaction.

**Comment by michwill** [comment]
Ok, I think that the problem is not gas usage, it's probably broadcasting several transactions with the same nonce (because transaction counter in geth accounts only for transactions which are already on blockchain?).
Here's an attempt to fix it, and, I think, we can try to test it on Felix
https://github.com/nucypher/nucypher/pull/1427

**Comment by michwill** [comment]
Simpler fix here https://github.com/nucypher/nucypher/pull/1430

**Pull request closed without merging**
