### PR TITLE
Updates web3 usage to version 4.3.0

### PR DESCRIPTION
**Pull request by szotov**

### CODE REVIEW

**Comment by KPrasch** [comment]
Cool - ill see if we can get a `Pipfile.lock`, once again.

**Comment by szotov** [comment]
py-evm is still 0.2.0a18
https://github.com/ethereum/eth-tester/issues/99

**Comment by KPrasch** [comment]
Yep - agreed this is the only working configuration at present: 
```
py-solc = "*"
py-evm = "==0.2.0a18"
eth-tester = "==0.1.0b27"
"web3" = "==4.3.0"
```

**Comment by KPrasch** [comment]
Hmm, Still cannot seem to lock the dependencies. 

```
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches cryptography<3.0.0,==2.3.dev1,>=2.0.3
```

**Pull request merged**
