### PR TITLE
[WIP] Verifying certificate when talking to node.

### LINKED ISSUE #60: Establish certificate-like authentication for public keys.
Is there currently a smart contract template for publishing and signing public key fingerprints?  Is there an implementation of TLS using this?

### PR DESCRIPTION
**Pull request by jMyles**
We've always used `verify=False` when talking to nodes via TLS.  But that's really not necessary. 

Fixes #60.

### CODE REVIEW

**Comment by jMyles** [comment]
I like these tools for examining the TLS offering:

http://www.taddong.com/en/lab.html#TLSSLED

**Comment by tuxxy** [comment]
@jMyles What are you using from the list?

**Comment by jMyles** [comment]
Well TLSSLed (to which the link directly points) is a favorite of mine.  Easy reliable way to look at the actual TLS details for a HTTPS server.

**Comment by jMyles** [comment]
Subsumed by #424.

**Pull request closed without merging**
