### PR TITLE
Code Coverage

### PR DESCRIPTION
**Pull request by derekpierre**
**Type of PR:**
- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [x] Other

**Required reviews:** 
- [X] 1
- [ ] 2
- [ ] 3

**What this does:**
Add code coverage.

### CODE REVIEW

**Review by theref — APPROVED** [review]
This is extremely useful, really looking forward to being able to get some insight on areas we may have overlooked

**Review by KPrasch — APPROVED** [review]
👏🏻

**Comment by theref** [comment]
Will merge once a release note is added 🚀

**Comment by derekpierre** [comment]
> Will merge once a release note is added 🚀

Code coverage is internal and just for our dev use. I don't think it should be included in the release notes.

**Pull request merged**
