### PR TITLE
Prometheus Memory

### PR DESCRIPTION
**Pull request by derekpierre**
**Type of PR:**
- [X] Bugfix
- [ ] Feature
- [ ] Documentation
- [ ] Other

**Required reviews:** 
- [x] 1
- [ ] 2
- [ ] 3

Investigation of potential prometheus memory issues.

*For reviewers*
It would be great if someone with a worklock allocation could run their node briefly with prometheus to ensure the worklock collectors work appropriately - worklock collectors are not tested on testnets.

### CODE REVIEW

**Comment by KPrasch** [comment]
> collectors were holding on to references of Contract Agent instances

Why do you think this causes growing memory consumption?

**Comment by derekpierre** [comment]
> Why do you think this causes growing memory consumption?

It's not that I thought this causes the memory consumption, it was just something that I noticed and thought was weird. My memory testing pre and post change did not yield any noticeable change - and that was expected. Figured it was good to improve the design anyway.

**Comment by KPrasch** [comment]
Ah, gotcha.  So this PR doesn't really have anything to do with prometheus memory usage, rather it's just an adjustment to collectors?

**Comment by derekpierre** [comment]
> Ah, gotcha. So this PR doesn't really have anything to do with prometheus memory usage, rather it's just an adjustment to collectors?

👍  - yep, the memory investigation didn't lead anywhere other than me discovering this non-associated issue.

**Review by KPrasch — APPROVED** [review]

**Pull request merged**
