### PR TITLE
[WIP] Fixes #1820: Handle invalid or missing certificate pseudonyms

### LINKED ISSUE #1820: Handle missing wallet address on TLS certificates
```
Traceback (most recent call last):
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/kieran/Git/nucypher/nucypher/network/sensors.py", line 85, in handle_measurement_errors
    failure.raiseException()
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/python/failure.py", line 488, in raiseException
    raise self.value.with_traceback(self.tb)
  File "/home/kieran/.local/share/virtualenvs/nucypher-9CH2v_st/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/kieran/Git/nucypher/nucypher/network/sensors.py", line 134, in maintain
    self.measure()
  File "/home/kieran/Git/nucypher/nucypher/network/sensors.py", line 183, in measure
    certificate_filepath = self._ursula.node_storage.store_node_certificate(certificate=certificate)
  File "/home/kieran/Git/nucypher/nucypher/config/storages.py", line 499, in store_node_certificate
    certificate_filepath = self._write_tls_certificate(certificate=certificate, force=force)
  File "/home/kieran/Git/nucypher/nucypher/config/storages.py", line 102, in _write_tls_certificate
    pseudonym = certificate.subject.get_attributes_for_oid(NameOID.PSEUDONYM)[0]
builtins.IndexError: list index out of range

```

### PR DESCRIPTION
**Pull request by KPrasch**

### CODE REVIEW

**Comment by KPrasch** [comment]
Sanity check here: which Ursula address belongs in the certificate?

**Comment by jMyles** [comment]
It has to be the Worker, right?  It's possible that it's more ideal for it to be the Staker, but then we'd need logic to sign the Worker's verifying trinket with the wallet secret, which we don't have right now.

So, Worker.

**Comment by KPrasch** [comment]
@jMyles - How much / if any of this PR is supplanted by #1741 ?

**Comment by KPrasch** [comment]
Closing for staleness - Will reopen post #1741

**Pull request closed without merging**
