### PR TITLE
Remove license header from modules

### PR DESCRIPTION
**Pull request by KPrasch**
**Type of PR:**
Other

**Required reviews:** 
1

**Note**
I will cleanup the +186 newline additions in a follow-up PR

### CODE REVIEW

**Review by manumonti — APPROVED** [review]
What a pleasure to see all these headers deleted 🔝

**Comment by derekpierre** [comment]
So, the `LICENSE` file in `nucypher` directory is sufficient for indicating AGPLv3 then?

I'm trying to find our original motivation for the header and pre-commit hook:
- https://github.com/nucypher/nucypher/issues/2012 (is this you @KPrasch 😝 j/k)
- https://github.com/nucypher/nucypher/pull/514

If we are removing it, the `.nucypher-license` file in the `nucypher` directory should be removed as well. It was added for the pre-commit hook (https://github.com/nucypher/nucypher/pull/2019).

**Comment by derekpierre** [comment]
> I will cleanup the +186 newline additions in a follow-up PR

If you are going to touch all of the files again, might be best to just include those changes in this PR...

**Comment by KPrasch** [comment]
> If you are going to touch all of the files again, might be best to just include those changes in this PR...

I'd like to optimize imports project-wide, but that diff will be harder to look at.  This is a tidy diff that's easier to review.

**Pull request merged**
