### PR TITLE
Fix "invalid escape sequence" warnings for regexes in test_status

### PR DESCRIPTION
**Pull request by fjarri**
Just a small fix for annoying warnings. Turn regex f-strings into raw f-strings.

### CODE REVIEW

**Comment by cygnusv** [comment]
This is fixed in biznaga, so perhaps it's better to just wait for it.

**Comment by fjarri** [comment]
Uhh, sorry, should have checked. These epics sure have everything in them.

**Comment by KPrasch** [comment]
Looks ready to merge but needs a rebase.

**Comment by KPrasch** [comment]
Included in Biznaga.

**Pull request closed without merging**
