### PR TITLE
Update docs configuration files

### PR DESCRIPTION
**Pull request by derekpierre**
**Type of PR:**
- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [X] Other

**Required reviews:** 
- [X] 1
- [ ] 2
- [ ] 3

**What this does:**
Updates docs configuration to use python 3.8, and new image.

### CODE REVIEW

**Comment by derekpierre** [comment]
@KPrasch any objection to me merging?

**Review by manumonti — APPROVED** [review]
Not sure if this should be reviewed by Kieran specifically, but looks good to me

**Review by cygnusv — APPROVED** [review]
Looks good! Any reason to leave the news fragment empty?

**Review by KPrasch — APPROVED** [review]

**Comment by derekpierre** [comment]
> Looks good! Any reason to leave the news fragment empty?

We chatted already, but just to close the loop here in case others are interested. 

The `dev` newsfragments are really more internal-focused entries for the release notes (kind of like a dev changelog) and are typically empty. The audience for our release notes are really users/adopters who don't particularly care about internal configuration file or CI changes etc., so typically dev newsfragments are left empty. The empty dev newsfragments are listed in the release notes under `Internal Development Tasks` and are shown as a link to the PR with the PR number as the linked text and no additional description.

**Pull request merged**
