### PR TITLE
Include changes and release notes from v5.3.1 hotfix in `main`

### PR DESCRIPTION
**Pull request by derekpierre**
**Type of PR:**
- [ ] Bugfix
- [ ] Feature
- [ ] Documentation
- [X] Other

**Required reviews:** 
- [ ] 1
- [X] 2
- [ ] 3

Related to #2769 .

No newsfragment necessary, already incorporated as part of original hotfix, and updated releases page.

**For reviewers**
Is this the best way to reconcile with `tags/v5.3.1`?

### CODE REVIEW

**Comment by vepkenez** [comment]
The question of whether or not to merge this into main is if we can figure out #2770 before our next release right?

**Comment by derekpierre** [comment]
> The question of whether or not to merge this into main is if we can figure out #2770 before our next release right?

My thought here was that we need to merge this PR now since there is currently a release that we put out (v5.3.1) that is not documented in our docs (releases page - https://docs.nucypher.com/en/latest/release_notes/releases.html), and the code isn't in `main`. 

#2770 is really a follow-up type issue. This is the workaround until #2770 and we can prioritize it as necessary moving forward; it can adjust/remove the changes made as necessary.

**Comment by vepkenez** [comment]
> > The question of whether or not to merge this into main is if we can figure out #2770 before our next release right?
> 
> My thought here was that we need to merge this PR now since there is currently a release that we put out (v5.3.1) that is not documented in our docs (releases page - https://docs.nucypher.com/en/latest/release_notes/releases.html), and the code isn't in `main`.
> 
> #2770 is really a follow-up type issue. This is the workaround until #2770 and we can prioritize it as necessary moving forward; it can adjust/remove the changes made as necessary.

Ok good point!  Lets do it.

**Review by vepkenez — APPROVED** [review]

**Comment by derekpierre** [comment]
Do we need to pick - https://github.com/nucypher/nucypher/commit/2aa615c613f43cd4ab846084c995b7b6138f530b?

**Comment by derekpierre** [comment]
> Do we need to pick - 2aa615c?

Picked and force-pushed.

**Comment by derekpierre** [comment]
@KPrasch is this PR sufficient?

**Review by KPrasch — APPROVED** [review]

**Pull request merged**
