### PR TITLE
[WIP] Make Ursula web status hideous in a different way

### PR DESCRIPTION
**Pull request by KPrasch**
Use default bootstrap styles to improve visual presentation of the Ursula web status page.

### CODE REVIEW

**Comment by derekpierre** [comment]
@KPrasch - Side Note: I am looking into possibly using Plotly Dash for the status page. Then we could do something like the following:
```
# Status Page
status_app = UrsulaStatus(ursula_node=known_node,
                          title='Ursula Status',
                          flask_server=rest_app,
                          route_url='/status/')
```
where the UrsulaStatus class creates a Dash application. This can then be used from either learning_monitor (with Moe) or the rest server.

Something similar could be done in the future for other characters if needed.

Still playing around though

**Comment by derekpierre** [comment]
@jMyles Haha 😂 .

**Comment by KPrasch** [comment]
Rebased over #802

**Comment by KPrasch** [comment]
Closing due to staleness.

**Pull request closed without merging**
